// account
export const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

//todo: redundant
export const LOGOUT = 'LOGOUT';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILURE = 'UPDATE_USER_INFO_FAILURE';


export const PAYMENT_IGNORE_REQUEST = 'PAYMENT_IGNORE_REQUEST';
export const PAYMENT_IGNORE_SUCCESS = 'PAYMENT_IGNORE_SUCCESS';
export const PAYMENT_IGNORE_FAILURE = 'PAYMENT_IGNORE_FAILURE';

export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILURE = 'PAYMENT_FAILURE';

export const CHECK_PAYMENT_STATUS_REQUEST = 'CHECK_PAYMENT_STATUS_REQUEST';
export const CHECK_PAYMENT_STATUS_SUCCESS = 'CHECK_PAYMENT_STATUS_SUCCESS';
export const CHECK_PAYMENT_STATUS_FAILURE = 'CHECK_PAYMENT_STATUS_FAILURE';


export const PROVINCE_DETAILS_REQUEST = 'PROVINCE_DETAILS_REQUEST';
export const PROVINCE_DETAILS_SUCCESS = 'PROVINCE_DETAILS_SUCCESS';
export const PROVINCE_DETAILS_FAILURE = 'PROVINCE_DETAILS_FAILURE';

export const PROVINCE_REQUEST = 'PROVINCE_REQUEST';
export const PROVINCE_SUCCESS = 'PROVINCE_SUCCESS';
export const PROVINCE_FAILURE = 'PROVINCE_FAILURE';

export const CITY_DETAILS_REQUEST = 'CITY_DETAILS_REQUEST';
export const CITY_DETAILS_SUCCESS = 'CITY_DETAILS_SUCCESS';
export const CITY_DETAILS_FAILURE = 'CITY_DETAILS_FAILURE';

export const CITY_REQUEST = 'CITY_REQUEST';
export const CITY_SUCCESS = 'CITY_SUCCESS';
export const CITY_FAILURE = 'CITY_FAILURE';

export const SCHOOL_REQUEST = 'SCHOOL_REQUEST';
export const SCHOOL_SUCCESS = 'SCHOOL_SUCCESS';
export const SCHOOL_FAILURE = 'SCHOOL_FAILURE';

// exam


export const EXAM_REGISTER_REQUEST = 'EXAM_REGISTER_REQUEST';
export const EXAM_REGISTER_SUCCESS = 'EXAM_REGISTER_SUCCESS';
export const EXAM_REGISTER_FAILURE = 'EXAM_REGISTER_FAILURE';

export const GET_STUDENT_EXAMS_REQUEST = 'GET_STUDENT_EXAMS_REQUEST';
export const GET_STUDENT_EXAMS_SUCCESS = 'GET_STUDENT_EXAMS_SUCCESS';
export const GET_STUDENT_EXAMS_FAILURE = 'GET_STUDENT_EXAMS_FAILURE';

export const GET_EXAM_REQUEST = 'GET_EXAM_REQUEST';
export const GET_EXAM_SUCCESS = 'GET_EXAM_SUCCESS';
export const GET_EXAM_FAILURE = 'GET_EXAM_FAILURE';

export const GET_QUESTION_REQUEST = 'GET_QUESTION_REQUEST';
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';
export const GET_QUESTION_FAILURE = 'GET_QUESTION_FAILURE';

export const SEND_ANSWER_REQUEST = 'SEND_ANSWER_REQUEST';
export const SEND_ANSWER_SUCCESS = 'SEND_ANSWER_SUCCESS';
export const SEND_ANSWER_FAILURE = 'SEND_ANSWER_FAILURE';

export const GET_ANSWER_REQUEST = 'GET_ANSWER_REQUEST';
export const GET_ANSWER_SUCCESS = 'GET_ANSWER_SUCCESS';
export const GET_ANSWER_FAILURE = 'GET_ANSWER_FAILURE';

// Redirect
export const REDIRECT = 'REDIRECT';
export const INIT_REDIRECT = 'INIT_REDIRECT';

// Mentor
export const GET_ANSWER_FOR_CORRECTION_REQUEST = 'GET_ANSWER_FOR_CORRECTION_REQUEST';
export const GET_ANSWER_FOR_CORRECTION_SUCCESS = 'GET_ANSWER_FOR_CORRECTION_SUCCESS';
export const GET_ANSWER_FOR_CORRECTION_FAILURE = 'GET_ANSWER_FOR_CORRECTION_FAILURE';

export const SET_ANSWER_SCORE_REQUEST = 'SET_ANSWER_SCORE_REQUEST';
export const SET_ANSWER_SCORE_SUCCESS = 'SET_ANSWER_SCORE_SUCCESS';
export const SET_ANSWER_SCORE_FAILURE = 'SET_ANSWER_SCORE_FAILURE';

//Toast
export const INIT_TOAST = 'INIT_TOAST';



export const TEAM_LOGIN_REQUEST = 'TEAM_LOGIN_REQUEST';
export const TEAM_LOGIN_SUCCESS = 'TEAM_LOGIN_SUCCESS';
export const TEAM_LOGIN_FAILURE = 'TEAM_LOGIN_FAILURE';

export const TEAM_DATA_REQUEST = 'TEAM_DATA_REQUEST';
export const TEAM_DATA_SUCCESS = 'TEAM_DATA_SUCCESS';
export const TEAM_DATA_FAILURE = 'TEAM_DATA_FAILURE';

export const REQUEST_PROBLEM_REQUEST = 'REQUEST_PROBLEM_REQUEST';
export const REQUEST_PROBLEM_SUCCESS = 'REQUEST_PROBLEM_SUCCESS';
export const REQUEST_PROBLEM_FAILURE = 'REQUEST_PROBLEM_FAILURE';

export const SUBMIT_ANSWER_REQUEST = 'SUBMIT_ANSWER_REQUEST';
export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS';
export const SUBMIT_ANSWER_FAILURE = 'SUBMIT_ANSWER_FAILURE';

export const GET_AUCTION_PROBLEMS_REQUEST = 'GET_AUCTION_PROBLEMS_REQUEST';
export const GET_AUCTION_PROBLEMS_SUCCESS = 'GET_AUCTION_PROBLEMS_SUCCESS';
export const GET_AUCTION_PROBLEMS_FAILURE = 'GET_AUCTION_PROBLEMS_FAILURE';

export const PUT_PROBLEM_IN_AUCTION_REQUEST = 'PUT_PROBLEM_IN_AUCTION_REQUEST';
export const PUT_PROBLEM_IN_AUCTION_SUCCESS = 'PUT_PROBLEM_IN_AUCTION_SUCCESS';
export const PUT_PROBLEM_IN_AUCTION_FAILURE = 'PUT_PROBLEM_IN_AUCTION_FAILURE';

export const GET_PROBLEM_FROM_AUCTION_REQUEST = 'GET_PROBLEM_FROM_AUCTION_REQUEST';
export const GET_PROBLEM_FROM_AUCTION_SUCCESS = 'GET_PROBLEM_FROM_AUCTION_SUCCESS';
export const GET_PROBLEM_FROM_AUCTION_FAILURE = 'GET_PROBLEM_FROM_AUCTION_FAILURE';

export const GET_PROBLEMS_REQUEST = 'GET_PROBLEMS_REQUEST';
export const GET_PROBLEMS_SUCCESS = 'GET_PROBLEMS_SUCCESS';
export const GET_PROBLEMS_FAILURE = 'GET_PROBLEMS_FAILURE';

export const GET_PROBLEM_REQUEST = 'GET_PROBLEM_REQUEST';
export const GET_PROBLEM_SUCCESS = 'GET_PROBLEM_SUCCESS';
export const GET_PROBLEM_FAILURE = 'GET_PROBLEM_FAILURE';


export const GET_UNCORRECTED_PROBLEMS_REQUEST = 'GET_UNCORRECTED_PROBLEMS_REQUEST';
export const GET_UNCORRECTED_PROBLEMS_SUCCESS = 'GET_UNCORRECTED_PROBLEMS_SUCCESS';
export const GET_UNCORRECTED_PROBLEMS_FAILURE = 'GET_UNCORRECTED_PROBLEMS_FAILURE';

export const SUBMIT_PROBLEM_SCORE_REQUEST = 'SUBMIT_PROBLEM_SCORE_REQUEST';
export const SUBMIT_PROBLEM_SCORE_SUCCESS = 'SUBMIT_PROBLEM_SCORE_SUCCESS';
export const SUBMIT_PROBLEM_SCORE_FAILURE = 'SUBMIT_PROBLEM_SCORE_FAILURE';


////////////////////////////////////

export const GET_PLAYER_INFO_REQUEST = 'GET_PLAYER_INFO_REQUEST';
export const GET_PLAYER_INFO_SUCCESS = 'GET_PLAYER_INFO_SUCCESS';
export const GET_PLAYER_INFO_FAILURE = 'GET_PLAYER_INFO_FAILURE';

export const GET_ALL_SINGLE_PROBLEMS_REQUEST = 'GET_ALL_SINGLE_PROBLEMS_REQUEST';
export const GET_ALL_SINGLE_PROBLEMS_SUCCESS = 'GET_ALL_SINGLE_PROBLEMS_SUCCESS';
export const GET_ALL_SINGLE_PROBLEMS_FAILURE = 'GET_ALL_SINGLE_PROBLEMS_FAILURE';

export const GET_ALL_MULTIPLE_PROBLEMS_REQUEST = 'GET_ALL_MULTIPLE_PROBLEMS_REQUEST';
export const GET_ALL_MULTIPLE_PROBLEMS_SUCCESS = 'GET_ALL_MULTIPLE_PROBLEMS_SUCCESS';
export const GET_ALL_MULTIPLE_PROBLEMS_FAILURE = 'GET_ALL_MULTIPLE_PROBLEMS_FAILURE';

export const GET_ALL_SUBJECTS_REQUEST = 'GET_ALL_SUBJECTS_REQUEST';
export const GET_ALL_SUBJECTS_SUCCESS = 'GET_ALL_SUBJECTS_SUCCESS';
export const GET_ALL_SUBJECTS_FAILURE = 'GET_ALL_SUBJECTS_FAILURE';

export const GET_RANDOM_SINGLE_PROBLEM_REQUEST = 'GET_RANDOM_SINGLE_PROBLEM_REQUEST';
export const GET_RANDOM_SINGLE_PROBLEM_SUCCESS = 'GET_RANDOM_SINGLE_PROBLEM_SUCCESS';
export const GET_RANDOM_SINGLE_PROBLEM_FAILURE = 'GET_RANDOM_SINGLE_PROBLEM_FAILURE';

export const GET_RANDOM_MULTIPLE_PROBLEM_REQUEST = 'GET_RANDOM_MULTIPLE_PROBLEM_REQUEST';
export const GET_RANDOM_MULTIPLE_PROBLEM_SUCCESS = 'GET_RANDOM_MULTIPLE_PROBLEM_SUCCESS';
export const GET_RANDOM_MULTIPLE_PROBLEM_FAILURE = 'GET_RANDOM_MULTIPLE_PROBLEM_FAILURE';

export const GET_SPECIFIC_SINGLE_PROBLEM_REQUEST = 'GET_SPECIFIC_SINGLE_PROBLEM_REQUEST';
export const GET_SPECIFIC_SINGLE_PROBLEM_SUCCESS = 'GET_SPECIFIC_SINGLE_PROBLEM_SUCCESS';
export const GET_SPECIFIC_SINGLE_PROBLEM_FAILURE = 'GET_SPECIFIC_SINGLE_PROBLEM_FAILURE';

export const GET_SPECIFIC_MULTIPLE_PROBLEM_REQUEST = 'GET_SPECIFIC_MULTIPLE_PROBLEM_REQUEST';
export const GET_SPECIFIC_MULTIPLE_PROBLEM_SUCCESS = 'GET_SPECIFIC_MULTIPLE_PROBLEM_SUCCESS';
export const GET_SPECIFIC_MULTIPLE_PROBLEM_FAILURE = 'GET_SPECIFIC_MULTIPLE_PROBLEM_FAILURE';

export const SUBMIT_SINGLE_PROBLEM_ANSWER_REQUEST = 'SUBMIT_SINGLE_PROBLEM_ANSWER_REQUEST';
export const SUBMIT_SINGLE_PROBLEM_ANSWER_SUCCESS = 'SUBMIT_SINGLE_PROBLEM_ANSWER_SUCCESS';
export const SUBMIT_SINGLE_PROBLEM_ANSWER_FAILURE = 'SUBMIT_SINGLE_PROBLEM_ANSWER_FAILURE';

export const SUBMIT_MULTIPLE_PROBLEM_ANSWER_REQUEST = 'SUBMIT_MULTIPLE_PROBLEM_ANSWER_REQUEST';
export const SUBMIT_MULTIPLE_PROBLEM_ANSWER_SUCCESS = 'SUBMIT_MULTIPLE_PROBLEM_ANSWER_SUCCESS';
export const SUBMIT_MULTIPLE_PROBLEM_ANSWER_FAILURE = 'SUBMIT_MULTIPLE_PROBLEM_ANSWER_FAILURE';

export const GET_PROBLEM_HINTS_REQUEST = 'GET_PROBLEM_HINTS_REQUEST';
export const GET_PROBLEM_HINTS_SUCCESS = 'GET_PROBLEM_HINTS_SUCCESS';
export const GET_PROBLEM_HINTS_FAILURE = 'GET_PROBLEM_HINTS_FAILURE';

export const SUBMIT_NEW_HINT_REQUEST = 'SUBMIT_NEW_HINT_REQUEST';
export const SUBMIT_NEW_HINT_SUCCESS = 'SUBMIT_NEW_HINT_SUCCESS';
export const SUBMIT_NEW_HINT_FAILURE = 'SUBMIT_NEW_HINT_FAILURE';

export const PLAYER_SINGLE_PROBLEM_FOR_CORRECTION_REQUEST = 'PLAYER_SINGLE_PROBLEM_FOR_CORRECTION_REQUEST';
export const PLAYER_SINGLE_PROBLEM_FOR_CORRECTION_SUCCESS = 'PLAYER_SINGLE_PROBLEM_FOR_CORRECTION_SUCCESS';
export const PLAYER_SINGLE_PROBLEM_FOR_CORRECTION_FAILURE = 'PLAYER_SINGLE_PROBLEM_FOR_CORRECTION_FAILURE';

export const CORRECT_ANSWER_REQUEST = 'CORRECT_ANSWER_REQUEST';
export const CORRECT_ANSWER_SUCCESS = 'CORRECT_ANSWER_SUCCESS';
export const CORRECT_ANSWER_FAILURE = 'CORRECT_ANSWER_FAILURE';

